### ISSUE TITLE
replace panic

### ISSUE THREAD

**Issue by teverett** [cosmos-ssi/cosmos#36]
wrap it in a macro that provides the line and file

**Comment by kurtmweber** [comment]
Ha!  I literally started working on exactly this earlier today, but the way I was doing it was requiring some weird preprocessor magic that I haven't quite been able to wrap my head around yet.

**Comment by teverett** [comment]
This might help

https://github.com/cosmos-ssi/cosmos/blob/master/kernel/sys/debug/assert.h

**Comment by kurtmweber** [comment]
Using kprintf was my initial thought, but it seemed like a good idea to minimize the complexity of what functions get called as much as possible because of the kind of potentially fragile scenarios in which panic can get called.

**Comment by kurtmweber** [comment]
Actually, for some reason I was thinking kprintf relied on kmalloc, which would be REALLY iffy to use in a panic situation, but looking at it I see that it doesn't.  It might still break if there's an issue with allocating stack space, but that could also be the case with panic as it is now, so...
