### ISSUE TITLE
boot.asm:15: error: byte data exceeds bounds

### ISSUE THREAD

**Issue by jschnurr** [cosmos-ssi/cosmos#49]
I noticed that nasm was raising a warning, and because the nasm flags didn't specify -Werror, I had not noticed it.

Here's what I get with -Werror enabled on Ubuntu:

```bash
nasm -O0 -Werror -f bin boot.asm -o boot.bin
boot.asm:15: error: byte data exceeds bounds [-w+error=number-overflow]
```

There are no noticeable side effects.

**Comment by kurtmweber** [comment]
fixed, it was writing a too-large value into an 8-bit register
